import express from 'express';
import { GoogleGenAI, Modality } from '@google/genai';

const router = express.Router();

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

router.post('/', async (req, res) => {
    const { imageBase64, mimeType, prompt } = req.body;

    if (!imageBase64 || !mimeType || !prompt) {
        return res.status(400).json({ error: 'Image data, mimeType, and prompt are required.' });
    }

    try {
        const imagePart = {
            inlineData: {
                data: imageBase64,
                mimeType: mimeType,
            },
        };

        const textPart = {
            text: prompt,
        };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: { parts: [imagePart, textPart] },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        // Extract the generated image data
        const generatedPart = response.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
        if (generatedPart?.inlineData) {
            res.json({ imageBase64: generatedPart.inlineData.data, mimeType: generatedPart.inlineData.mimeType });
        } else {
            throw new Error("No image was generated by the AI.");
        }

    } catch (error) {
        console.error("Error editing image with Gemini API:", error);
        res.status(500).json({ error: 'Failed to edit image with AI.' });
    }
});

export default router;