
import { GoogleGenAI, Type, Modality } from "@google/genai";
import { ModelData } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });
const model = 'gemini-2.5-flash';

export const getFeasibilitySuggestion = async (designPrompt: string): Promise<string> => {
    // ... existing function ...
    return "Feasibility check is currently offline.";
};

export const modernizeBlueprint = async (imageBase64: string, mimeType: string): Promise<{description: string; model: ModelData}> => {
    // ... existing function ...
    throw new Error("Blueprint modernization is currently offline.");
};

export const editImageWithGemini = async (imageBase64: string, mimeType: string, prompt: string): Promise<{ imageBase64: string; mimeType: string }> => {
  try {
    const imagePart = { inlineData: { data: imageBase64, mimeType: mimeType } };
    const textPart = { text: prompt };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [imagePart, textPart] },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const generatedPart = response.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
    if (generatedPart?.inlineData) {
      return { imageBase64: generatedPart.inlineData.data, mimeType: generatedPart.inlineData.mimeType };
    } else {
      throw new Error("No image was generated by the AI.");
    }
  } catch (error) {
    console.error("Error editing image with Gemini API:", error);
    throw new Error('Failed to edit image with AI.');
  }
};

export const generateVideoWithVeo = async (imageBase64: string, mimeType: string, prompt: string, aspectRatio: '16:9' | '9:16'): Promise<{ videoUri: string }> => {
  // Per Veo guidelines, a new instance can be created to ensure the latest key.
  const veoAi = new GoogleGenAI({ apiKey: process.env.API_KEY! });
  try {
    let operation = await veoAi.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt,
      image: { imageBytes: imageBase64, mimeType: mimeType },
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: aspectRatio
      }
    });

    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await veoAi.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (downloadLink) {
      return { videoUri: downloadLink };
    } else {
      throw new Error("Video generation completed, but no URI was returned.");
    }
  } catch (error) {
    console.error("Error generating video with Veo API:", error);
    if (error instanceof Error && error.message.includes("Requested entity was not found.")) {
      throw new Error('API key may be invalid. Please re-select your API key.');
    }
    throw new Error('Failed to generate video with AI.');
  }
};
